import { 
  Type,
  FileText,
  Hash,
  Calendar,
  Mail,
  Phone,
  MapPin,
  List,
  ToggleLeft,
  Upload
} from "lucide-react";
import { FormTemplate, FieldType } from "./types";

// Données des types de textes juridiques depuis l'onglet "Types de textes"
export const legalTypes: FormTemplate[] = [
  { value: "constitution", label: "Constitution", code: "CON", fields: ["titre", "numero", "date_promulgation", "journal_officiel", "contenu", "domaine_juridique", "status", "auteur", "organisation"] },
  { value: "accord_international", label: "Accord International", code: "ACI", fields: ["titre", "numero", "date_signature", "parties", "contenu", "domaine", "ratification", "organisation"] },
  { value: "convention_internationale", label: "Convention Internationale", code: "CVI", fields: ["titre", "numero", "date_signature", "parties", "contenu", "domaine", "ratification", "organisation"] },
  { value: "code", label: "Code", code: "COD", fields: ["titre", "type_code", "derniere_modification", "livre", "titre_livre", "chapitre", "section", "article", "organisation"] },
  { value: "loi_organique", label: "Loi Organique", code: "LOR", fields: ["titre", "numero", "date_promulgation", "journal_officiel", "contenu", "domaine_juridique", "organisation"] },
  { value: "loi", label: "Loi", code: "LOI", fields: ["titre", "numero", "date_promulgation", "journal_officiel", "contenu", "domaine_juridique", "status", "auteur", "organisation"] },
  { value: "ordonnance", label: "Ordonnance", code: "ORD", fields: ["titre", "numero", "date_signature", "president", "contexte", "domaine", "ratification", "effet", "organisation"] },
  { value: "decret_legislatif", label: "Décret Législatif", code: "DLG", fields: ["titre", "numero", "date_signature", "signataire", "contenu", "texte_reference", "organisation"] },
  { value: "decret_presidentiel", label: "Décret Présidentiel", code: "DPR", fields: ["titre", "numero", "date_signature", "signataire", "contenu", "texte_reference", "organisation"] },
  { value: "decret_executif", label: "Décret Exécutif", code: "DEC", fields: ["titre", "numero", "date_signature", "signataire", "contenu", "texte_reference", "ministere", "application", "organisation"] },
  { value: "arrete", label: "Arrêté", code: "ARR", fields: ["titre", "numero", "ministere", "date_signature", "objet", "application", "abrogation", "publication", "organisation"] },
  { value: "arrete_interministerielle", label: "Arrêté interministérielle", code: "AIM", fields: ["titre", "numero", "ministeres", "date_signature", "objet", "application", "organisation"] },
  { value: "arrete_ministerielle", label: "Arrêté ministérielle", code: "ARM", fields: ["titre", "numero", "ministere", "date_signature", "objet", "application", "organisation"] },
  { value: "decision", label: "Décision", code: "DEC", fields: ["titre", "numero", "autorite", "date_signature", "objet", "beneficiaire", "organisation"] },
  { value: "decision_interministerielle", label: "Décision interministérielle", code: "DIM", fields: ["titre", "numero", "ministeres", "date_signature", "objet", "organisation"] },
  { value: "avis", label: "Avis", code: "AVI", fields: ["titre", "numero", "autorite", "date_signature", "objet", "organisation"] },
  { value: "proclamation", label: "Proclamation", code: "PRO", fields: ["titre", "numero", "autorite", "date_signature", "objet", "organisation"] },
  { value: "instruction", label: "Instruction", code: "INS", fields: ["titre", "numero", "autorite", "date_signature", "objet", "organisation"] },
  { value: "instruction_interministerielle", label: "Instruction interministérielle", code: "IIM", fields: ["titre", "numero", "ministeres", "date_signature", "objet", "organisation"] },
  { value: "reglements", label: "Règlements", code: "REG", fields: ["titre", "numero", "autorite", "date_signature", "objet", "organisation"] },
  { value: "circulaire", label: "Circulaire", code: "CIR", fields: ["titre", "numero", "autorite", "date_signature", "objet", "organisation"] },
  { value: "circulaire_interministerielle", label: "Circulaire interministérielle", code: "CIM", fields: ["titre", "numero", "ministeres", "date_signature", "objet", "organisation"] },
  { value: "convention", label: "Convention", code: "COV", fields: ["titre", "numero", "parties", "date_signature", "objet", "organisation"] },
  { value: "note", label: "Note", code: "NOT", fields: ["titre", "numero", "autorite", "date_signature", "objet", "organisation"] },
  { value: "note_circulaire", label: "Note circulaire", code: "NCR", fields: ["titre", "numero", "autorite", "date_signature", "objet", "organisation"] },
  { value: "notification", label: "Notification", code: "NTF", fields: ["titre", "numero", "autorite", "date_signature", "objet", "destinataire", "organisation"] },
  { value: "communique", label: "Communiqué", code: "COM", fields: ["titre", "numero", "autorite", "date_publication", "contenu", "organisation"] },
  { value: "correspondance", label: "Correspondance", code: "COR", fields: ["titre", "numero", "expediteur", "destinataire", "date", "objet", "organisation"] },
  { value: "deliberation", label: "Délibération", code: "DEL", fields: ["titre", "numero", "assemblee", "date_deliberation", "objet", "organisation"] },
  { value: "resolutions", label: "Résolutions", code: "RES", fields: ["titre", "numero", "assemblee", "date_resolution", "objet", "organisation"] },
  { value: "declaration", label: "Déclaration", code: "DCL", fields: ["titre", "numero", "declarant", "date_declaration", "contenu", "organisation"] },
  { value: "bulletin_information", label: "Bulletin d'information", code: "BIN", fields: ["titre", "numero", "editeur", "date_publication", "contenu", "organisation"] },
  { value: "jurisprudence", label: "Jurisprudence", code: "JUR", fields: ["titre", "numero", "juridiction", "date_decision", "contenu", "organisation"] },
  { value: "cahier_charge", label: "Cahier de charge", code: "CDC", fields: ["titre", "numero", "maitre_ouvrage", "date_approbation", "specifications", "organisation"] },
  { value: "cahier_clauses_administratives", label: "Cahier des clauses administratives générales", code: "CAG", fields: ["titre", "numero", "autorite", "date_approbation", "clauses", "organisation"] },
  { value: "discours", label: "Discours", code: "DIS", fields: ["titre", "orateur", "date_discours", "lieu", "contenu", "organisation"] },
  { value: "rapport_guide", label: "Rapport, Guide", code: "RAP", fields: ["titre", "numero", "auteur", "date_publication", "contenu", "organisation"] },
  { value: "plan_action", label: "Plan d'action", code: "PLA", fields: ["titre", "numero", "responsable", "date_debut", "objectifs", "organisation"] },
  { value: "bareme_norme", label: "Barème, Norme", code: "BAR", fields: ["titre", "numero", "autorite", "date_application", "specifications", "organisation"] },
  { value: "proces_verbal", label: "Procès-verbal", code: "PVB", fields: ["titre", "numero", "redacteur", "date_reunion", "contenu", "organisation"] }
];

// Données des catégories de procédures depuis l'onglet "Catégorie Procédures"  
export const procedureCategories: FormTemplate[] = [
  { value: "etat_civil", label: "État Civil", code: "ETI", fields: ["nom_procedure", "documents_requis", "delai_traitement", "cout", "lieu_depot", "conditions", "pieces_jointes", "observations", "organisation"] },
  { value: "urbanisme", label: "Urbanisme", code: "URB", fields: ["type_permis", "surface", "localisation", "documents_techniques", "frais", "commission", "zone", "contraintes", "organisation"] },
  { value: "commerce", label: "Commerce", code: "COM", fields: ["forme_juridique", "capital_social", "activite", "associes", "siege_social", "duree", "immatriculation", "taxes", "organisation"] },
  { value: "emploi", label: "Emploi", code: "EMP", fields: ["type_demande", "qualifications", "experience", "formation", "salaire_souhaite", "disponibilite", "organisation"] },
  { value: "sante", label: "Santé", code: "SAN", fields: ["type_service", "carte_assurance", "medecin_traitant", "specialite", "urgence", "rendez_vous", "organisation"] },
  { value: "education", label: "Éducation", code: "EDU", fields: ["niveau_etude", "etablissement", "diplome", "notes", "inscription", "annee_scolaire", "organisation"] },
  { value: "transport", label: "Transport", code: "TRA", fields: ["type_permis", "categorie_vehicule", "examen_medical", "formation", "cout_total", "validite", "restrictions", "renouvellement", "organisation"] },
  { value: "fiscalite", label: "Fiscalité", code: "FIS", fields: ["type_declaration", "periode_fiscale", "revenus", "charges", "impots", "penalites", "organisation"] }
];

export const formLists = {
  textes_juridiques: legalTypes,
  procedures_administratives: procedureCategories
};

export const formTypes = [
  { value: "textes_juridiques", label: "Textes Juridiques" },
  { value: "procedures_administratives", label: "Procédures Administratives" }
];

export const fieldTypes: FieldType[] = [
  { value: "text", label: "Texte", icon: Type },
  { value: "textarea", label: "Zone de texte", icon: FileText },
  { value: "number", label: "Nombre", icon: Hash },
  { value: "date", label: "Date", icon: Calendar },
  { value: "email", label: "Email", icon: Mail },
  { value: "tel", label: "Téléphone", icon: Phone },
  { value: "url", label: "URL", icon: MapPin },
  { value: "select", label: "Liste déroulante", icon: List },
  { value: "checkbox", label: "Case à cocher", icon: ToggleLeft },
  { value: "file", label: "Fichier", icon: Upload }
];

// Données des organisations depuis l'onglet "Organisation"
export const organizationOptions = [
  "Ministère de la santé et de la population",
  "Ministère de la santé publique",
  "Assemblée Populaire Nationale",
  "Autorité Nationale Indépendante des Elections",
  "Autorité de Régulation de la Poste et des Communications Électroniques",
  "Autorité de Régulation de la Poste et des Télécommunications",
  "Banque d'Algérie",
  "Conseil Constitutionnel",
  "Conseil National Economique, Social et Environnemental",
  "Conseil National de l'Investissement",
  "Conseil National des Droits de l'Homme",
  "Conseil Supérieur de la Magistrature",
  "Conseil de la Nation",
  "Conseil d'État",
  "Cour Constitutionnelle",
  "Cour Suprême",
  "Cour des comptes",
  "Haut conseil de la langue arabe",
  "Haut conseil islamique",
  "Haute Instance Indépendante de Surveillance des Élections",
  "Ministre de l'intérieur et des collectivités locales",
  "Ministre de la Famille et de la Condition Féminine",
  "Ministre de la Planification et de l'Aménagement du Territoire",
  "Ministre du Travail, de l'Emploi et des Affaires Sociales",
  "Ministère Délégué au Logement",
  "Ministère Délégué du Budget",
  "Ministère de la petite et moyenne entreprise",
  "Ministère de l'Action Sociale et de la Solidarité Nationale",
  "Ministère de l'Agriculture",
  "Ministère de l'Agriculture et de la Réforme Agraire",
  "Ministère de l'Agriculture et du développement rural",
  "Ministère de l'Agriculture, du Développement Rural et de la Pêche",
  "Ministère de l'Aménagement du Territoire de l'Urbanisme et de la Construction",
  "Ministère de l'Aménagement du territoire et de l'Environnement",
  "Ministère de l'Education Nationale",
  "Ministère de l'Education et de l'Enseignement Fondamental",
  "Ministère de l'Energie et des Industries Pétrochimiques",
  "Ministère de l'Enseignement Originel et des Affaires Religieuses",
  "Ministère de l'Enseignement Supérieur",
  "Ministère de l'Enseignement Supérieur et de la Recherche Scientifique",
  "Ministère de l'Environnement Urbain, du Tourisme et de l'Artisanat",
  "Ministère de l'Environnement et des Energies Renouvelables",
  "Ministère de l'Equipement et du Logement",
  "Ministère de l'Habitat et de l'Urbanisme",
  "Ministère de l'Industrie Pharmaceutique",
  "Ministère de l'Industrie et de l'Energie",
  "Ministère de l'Information",
  "Ministère de l'Information et de la Culture",
  "Ministère de l'Urbanisme, de la Construction et de l'Habitat",
  "Ministère de l'agriculture",
  "Ministère de l'agriculture et de la pêche",
  "Ministère de l'environnement",
  "Ministère de l'habitat",
  "Ministère de l'hydraulique",
  "Ministère de l'industrie",
  "Ministère de l'industrie et de la promotion des investissements",
  "Ministère de l'industrie et de la restructuration",
  "Ministère de l'industrie, de la petite et moyenne entreprise et de la promotion de l'investissement",
  "Ministère de l'intérieur",
  "Ministère de l'intérieur et de l'environnement",
  "Ministère de l'urbanisme et de la construction",
  "Ministère de l'économie",
  "Ministère de l'énergie et des mines",
  "Ministère de l'équipement",
  "Ministère de l'équipement et de l'aménagement du territoire",
  "Ministère de la Communication",
  "Ministère de la Culture",
  "Ministère de la Culture et de la Réforme Agraire",
  "Ministère de la Culture et des Arts",
  "Ministère de la Culture et du Tourisme",
  "Ministère de la Défense Nationale",
  "Ministère de la Formation Professionnelle",
  "Ministère de la Formation Professionnelle et du Travail",
  "Ministère de la Formation et de l'Enseignement Professionnel",
  "Ministère de la Jeunesse",
  "Ministère de la Jeunesse et des Sports",
  "Ministère de la Justice",
  "Ministère de la Participation et de la Coordination des Réformes",
  "Ministère de la Planification",
  "Ministère de la Poste et des Technologies de l'Information et de la Communication",
  "Ministère de la Poste, des Télécommunications, des Technologies et du Numérique",
  "Ministère de la Prospective et des Statistiques",
  "Ministère de la Protection Sociale",
  "Ministère de la Recherche Scientifique",
  "Ministère de la Recherche, à la Technologie et à l'Environnement",
  "Ministère de la Reconstruction, des Travaux Publics et des Transports",
  "Ministère de la Santé et des Affaires Sociales et des Universités",
  "Ministère de la Santé, de la Population et de la Réforme Hospitalière",
  "Ministère de la Solidarité Nationale",
  "Ministère de la Solidarité Nationale de la Famille et de la Condition de la Femme",
  "Ministère de la Solidarité Nationale, de la Famille et de la Communauté Nationale à l'Etranger",
  "Ministère de la Ville",
  "Ministère de la culture et de la communication",
  "Ministère de la micro-entreprise, des start-ups et de l'économie de la connaissance",
  "Ministère de la numérisation et des statistiques",
  "Ministère de la petite et moyenne entreprise et de l'artisanat",
  "Ministère de la poste et des télécommunications",
  "Ministère de la pêche et des productions halieutiques",
  "Ministère de la pêche et des ressources halieutiques",
  "Ministère de la santé",
  "Ministère de la transition énergétique et des énergies renouvelables",
  "Ministère de l'Emploi et de la Solidarité Nationale",
  "Ministère de l'Industrie et des Mines",
  "Ministère de l'Intérieur, des Collectivités Locales et de l'Aménagement du Territoire",
  "Ministère de l'aménagement du territoire, du tourisme et de l'artisanat",
  "Ministère de l'habitat, de l'urbanisme et de la ville",
  "Ministère de l'hydraulique de l'environnement et des forêts",
  "Ministère de l'intérieur, des collectivités locales, de l'environnement et de la réforme administrative",
  "Ministère de l'Énergie",
  "Ministère de l'énergie et des industries chimiques et pétrochimiques",
  "Ministère des Affaires Etrangères",
  "Ministère des Finances",
  "Présidence de la république"
];